name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: prepareEnv
      run: |
        go install github.com/go-bindata/go-bindata/...@latest
        go-bindata -version

    - name: build
      run: |
        make build
        make buildWindows
