name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: prepareEnv
      run: go install github.com/go-bindata/go-bindata/...@latest

    - name: build
      run: |
        go install github.com/go-bindata/go-bindata/...@latest
        make build
